services:
  mysql:
    container_name: 'mysql-container'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=cadastroninja'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
        - '3306:3306'